---
# Kustomization creates modified config file contents for a customized bundle image.
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
# Do not change this namespace - presently logging can only be installed in namespace/openshift-logging.
namespace: openshift-logging
images:
  # Do not change this name - this is the name we want to replace from ../../manager/manager.yaml
  - name: quay.io/openshift-logging/cluster-logging-operator
    # EDIT HERE: replace with the desired image name, without any tag.
    newName: quay.io/openshift-logging/cluster-logging-operator
    # EDIT HERE: replace with desired image tag. The tag must be a valid semantic version, see https://semver.org/
    newTag: 5.6.0-preview.1
patchesStrategicMerge:
  # EDIT THIS FILE: to control the related images used for for operands.
  - deployment_patch.yaml
# Resource list.
resources:
  - ../../manifests
