#! package-manifest: ./deploy/chart/catalog_resources/rh-operators/clusterlogging.v4.6.0.clusterserviceversion.yaml
packageName: cluster-logging
channels:
- name: "4.6"
  currentCSV: clusterlogging.v4.6.0
