#! package-manifest: ./deploy/chart/catalog_resources/rh-operators/clusterlogging.v4.7.0.clusterserviceversion.yaml
packageName: cluster-logging
channels:
- name: "tech-preview"
  currentCSV: clusterlogging.v5.2.0-preview.1
