apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: collect-audit-logs
rules:
- apiGroups:
  - logging.openshift.io
  resources:
  - logs
  verbs:
  - collect
  resourceNames:
  - audit