resources:
#- role.yaml
#- clusterrole_binding.yaml
#- role_binding.yaml
- metadata_reader_clusterrole.yaml
- prometheus_role.yaml
- prometheus_role_binding.yaml
- cluster-logging-operator_clusterrole.yaml
- cluster-logging-operator_clusterrolebinding.yaml
- cluster-logging-operator_role.yaml
- cluster-logging-operator_rolebinding.yaml
- collect-application-logs-clusterrole.yaml
- collect-audit-logs-clusterrole.yaml
- collect-infrastructure-logs-clusterrole.yaml
#- leader_election_role.yaml
#- leader_election_role_binding.yaml
# Comment the following 4 lines if you want to disable
# the auth proxy (https://github.com/brancz/kube-rbac-proxy)
# which protects your /metrics endpoint.
#- auth_proxy_service.yaml
#- auth_proxy_role.yaml
#- auth_proxy_role_binding.yaml
#- auth_proxy_client_clusterrole.yaml
