apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: log-collector-privileged-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: log-collector-privileged
subjects:
  - kind: ServiceAccount
    name: logcollector

