apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterloggings.logging.openshift.io
spec:
  group: logging.openshift.io
  names:
    kind: ClusterLogging
    listKind: ClusterLoggingList
    plural: clusterloggings
    singular: clusterlogging
  scope: Namespaced
  version: v1
  validation:
    openAPIV3Schema:
      type: object
      properties:
        metadata:
          description: Specification of the metadata for the cluster
          properties:
            name:
              description: The name of the clusterlogging object
              type: string
              enum:
              - "instance"
        spec:
          description: Specification of the desired behavior of the Logging cluster.
          type: object
          properties:
            managementState:
              description: Indicator if the resource is 'Managed' or 'Unmanaged' by the operator
              type: string
              enum:
              - "Managed"
              - "Unmanaged"
            visualization:
              description: Specification of the Visualization component for the cluster
              type: object
              nullable: true
              properties:
                type:
                  description: The type of Visualization to configure
                  type: string
                kibana:
                  description: Specification of the Kibana Visualization component
                  type: object
                  properties:
                    resources:
                      description: The resource requirements for Kibana
                      type: object
                      nullable: true
                      properties:
                        limits:
                          description: 'Limits describes the maximum amount of compute
                            resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                          type: object
                          nullable: true
                        requests:
                          description: 'Requests describes the minimum amount of compute
                            resources required. If Requests is omitted for a container,
                            it defaults to Limits if that is explicitly specified, otherwise
                            to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                          type: object
                          nullable: true
                    nodeSelector:
                      description: Define which Nodes the Pods are scheduled on.
                      type: object
                      nullable: true
                    replicas:
                      description: Number of instances to deploy for a Kibana deployment
                      format: int32
                      type: integer
                    proxySpec:
                      description: Specification of the Kibana Proxy component
                      type: object
                      properties:
                        resources:
                          description: The resource requirements for Kibana
                          type: object
                          nullable: true
                          properties:
                            limits:
                              description: 'Limits describes the maximum amount of compute
                                resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                              type: object
                              nullable: true
                            requests:
                              description: 'Requests describes the minimum amount of compute
                                resources required. If Requests is omitted for a container,
                                it defaults to Limits if that is explicitly specified, otherwise
                                to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                              type: object
                              nullable: true
                  required:
                  - replicas
              required:
              - type
            logStore:
              description: Specification of the Log Storage component for the cluster
              type: object
              nullable: true
              properties:
                type:
                  description: The type of Log Storage to configure
                  type: string
                elasticsearch:
                  description: Specification of the Elasticsearch Log Store component
                  type: object
                  properties:
                    resources:
                      description: The resource requirements for Kibana
                      type: object
                      nullable: true
                      properties:
                        limits:
                          description: 'Limits describes the maximum amount of compute
                            resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                          type: object
                          nullable: true
                        requests:
                          description: 'Requests describes the minimum amount of compute
                            resources required. If Requests is omitted for a container,
                            it defaults to Limits if that is explicitly specified, otherwise
                            to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                          type: object
                          nullable: true
                    nodeSelector:
                      description: Define which Nodes the Pods are scheduled on.
                      type: object
                      nullable: true
                    nodeCount:
                      description: Number of nodes to deploy for Elasticsearch
                      format: int32
                      type: integer
                    storage:
                      description: 'The storage specification for Elasticsearch data nodes'
                      type: object
                      nullable: true
                      properties:
                        size:
                          description: 'The capacity of storage to provision.'
                          type: string
                        storageClassName:
                          description: 'The class of storage to provision. More info: https://kubernetes.io/docs/concepts/storage/storage-classes/'
                          type: string
                    redundancyPolicy:
                      description: The policy towards data redundancy to specify the number of redundant primary shards
                      type: string
                      enum:
                      - "FullRedundancy"
                      - "MultipleRedundancy"
                      - "SingleRedundancy"
                      - "ZeroRedundancy"
                    proxy:
                      description: Specification of the Elasticsearch Proxy component
                      properties:
                        resources:
                          description: ResourceRequirements describes the compute
                            resource requirements.
                          nullable: true
                          properties:
                            limits:
                              description: 'Limits describes the maximum amount of
                                compute resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                              type: object
                            requests:
                              description: 'Requests describes the minimum amount
                                of compute resources required. If Requests is omitted
                                for a container, it defaults to Limits if that is
                                explicitly specified, otherwise to an implementation-defined
                                value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                              type: object
                          type: object
                      required:
                      - resources
                      type: object
                  required:
                  - nodeCount
                retentionPolicy:
                  description: Retention policy defines the maximum age for an index after which it should be deleted
                  type: object
                  nullable: true
                  properties:
                    application:
                      type: object
                      nullable: true
                      properties:
                        maxAge:
                          type: string
                    infra:
                      type: object
                      nullable: true
                      properties:
                        maxAge:
                          type: string
                    audit:
                      type: object
                      nullable: true
                      properties:
                        maxAge:
                          type: string
              required:
              - type
            collection:
              description: Specification of the Collection component for the cluster
              type: object
              nullable: true
              properties:
                logs:
                  description: Specification of Log Collection for the cluster
                  type: object
                  properties:
                    type:
                      description: The type of Log Collection to configure
                      type: string
                    fluentd:
                      description: Specification of the Fluentd Log Collection component
                      type: object
                      properties:
                        resources:
                          description: The resource requirements for Fluentd
                          type: object
                          nullable: true
                          properties:
                            limits:
                              description: 'Limits describes the maximum amount of compute
                                resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                              type: object
                              nullable: true
                            requests:
                              description: 'Requests describes the minimum amount of compute
                                resources required. If Requests is omitted for a container,
                                it defaults to Limits if that is explicitly specified, otherwise
                                to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                              type: object
                              nullable: true
                        nodeSelector:
                          description: Define which Nodes the Pods are scheduled on.
                          type: object
                          nullable: true
                  required:
                  - type
            curation:
              description: Specification of the Curation component for the cluster
              type: object
              nullable: true
              properties:
                type:
                  description: The kind of curation to configure
                  type: string
                curator:
                  type: object
                  description: The specification of curation to configure
                  properties:
                    resources:
                      type: object
                      description: The resource requirements for Curator
                      nullable: true
                      properties:
                        limits:
                          description: 'Limits describes the maximum amount of compute
                            resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                          type: object
                          nullable: true
                        requests:
                          description: 'Requests describes the minimum amount of compute
                            resources required. If Requests is omitted for a container,
                            it defaults to Limits if that is explicitly specified, otherwise
                            to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                          type: object
                          nullable: true
                    nodeSelector:
                      description: Define which Nodes the Pods are scheduled on.
                      type: object
                      nullable: true
                    schedule:
                      description: 'The cron schedule that the Curator job is run. Defaults to "30 3 * * *"'
                      type: string
                  required:
                  - schedule
              required:
              - type
        status:
          type: object
  subresources:
    status: {}
